[Serial]
portName=COM3

[TCP]
ip=192.168.1.20



[MotionUp]
voltage=10
frequency=100
timeuse=0

[MotionDown]
voltage=10
frequency=100
timeuse=0

[MotionLeft]
voltage=10
frequency=100
timeuse=0

[MotionRight]
voltage=10
frequency=100
timeuse=0

[MotionGather]
voltage=10
frequency=100
timeuse=0


[MotionHCentered]
voltage=10
frequency=100
timeuse=0


; 应用设置
[app]
autoConnect=true
version=1.2
description=Serial Debug Tool
recentFiles=file1.txt,file2.txt,file3.txt